### ISSUE TITLE
Alternatives to fine grained change to summaries

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#220]
We have been thinking about the number of calls needed to update HMRC, and would like to present you with three option and request your feedback upon them.

If you want to provide confidential feedback, please email SDST (please allow extra time for responses).
# Option 1

A resource for each summary. This is how the API is currently operates:

List/create incomes:

```
GET/POST /self-assessement/{utr}/{taxYear}/self-employments/{sourceId}/incomes
```

Get/update incomes:

```
GET/PUT /self-assessement/{utr}/{taxYear}/self-employments/{sourceId}/incomes/{summaryId}
```

The resource has the following fields:

```
{"id", "0001", "type": "Turnover", "amount": 10.00}
```
# Option 2a

A resource for each summary type, e.g. get/update all incomes:

```
GET/PUT /self-assessement/{utr}/{taxYear}/self-employments/{sourceId}/incomes
```

The resource is an array:

```
[
  {"id": "0001", "type": "Turnover", "amount": 10.00},
  {"id": "0002", "type": "Other", "amount": 20.00}
]
```

During a update, the following rules apply:
- Items without "id" are created.
- Items with "id" are updated.
- IDs that exist, but are missing are deleted.

You may have multiple values per key.
# Option 2b

A resource for each summary type, e.g. get/update all incomes:

```
GET/PUT /self-assessement/{utr}/{taxYear}/self-employments/{sourceId}/incomes
```

The resource is a map from type to amount:

```
{
 "turnover": 10.00,
 "other": 20.00
}
```

As keys within a map are unique, you can only have one value per key.
# Option 3

A resource for all summary types, e.g. get/update all summaries:

```
GET|PUT /self-assessement/{utr}/{taxYear}/self-employments/{sourceId}/summaries
```

The resource is a map from summary type to summary data:

```
{
  "incomes": {
    "turnover": 10.00,
    "other": 20.00
  },
  "expenses": {
    "rent": 30.00,
    "other": 40.00
  },
  "goodsAndServicesForOweUse": 1000,
  "balancingCharges": {
     "bpra": 50
  }
}
```

**Comment by P-Tracy** [comment]
Hi Alex

I found it a little hard to read without seeing the sequence, but my only issue with combining unrelated data in a single transaction is the concept of partial success.  

By submitting multiples in a single transaction, I'm assuming you'll follow the REST principle of a black and white response; so all succeed or all fail?  If this is the case, how would the consumer know which element was the issue?  Generally I think to support bulk uploads, you would need the error responses to be more verbose and targeted, which means the consumer needs to then start interrogating the content to determine the issue, rather than just reacting to a status code.  

I don't have an issue for GETs, obviously.  Just PUTs and POSTs.

We haven't started coding in earnest, but aren't we able to just execute all our transactions in parallel?  Given these resources are un-related, can't we just send them at once?  

Is the chattiness issue being raised by the consumers or by HMRC?

**Comment by alexec** [comment]
Hi Pauline,

Each HTTP request would be a transaction - i.e. either all the data is committed, or none. 

On the occasion that we have a problem with a single element of the request, then we provide a path in the response to highlight the problematic field. 

Is chattiness a concern for you? Do you have a preference on any of the above options?

Alex

**Comment by P-Tracy** [comment]
We haven't started coding in earnest yet, so we haven't experienced the chattiness issue yet.  

I'm not a fan of supporting lists of things as the failure scenarios are always problematic to support both from a supplier and consumer perspective.  However, if it's required for performance reasons and is a choice that the consumer can make (I can provide lists of 1 in parallel and not see the issues) then that becomes less of an issue for me.  

I would think it's quite a bad idea to support any form of combined PUT/POST where the provision of an ID is the distinguishing feature that will identify the different from an implementation perspective.  I would say keep the PUTs and POSTs discrete, and support lists only if you have to.

Is the throttling issue part of the reason this is causing problems for consumers just now?

**Comment by alexec** [comment]
@P-Tracy, when you say "I would think it's quite a bad idea to support any form of combined PUT/POST" please can I ask which option are you referring to? Do you have a preference on any of the above options?

**Comment by P-Tracy** [comment]
In order of preference, I'd go:

1. 1
2. 2a
3. 3
4. 2b

I don't actually know what I'm referring to with the combined PUT/POST.  I thought I'd read that you were going to allow the user to give a list of data and the code would determine under the covers whether something was a create or an update - but that's not what you've said at all.  Apologies!

**Comment by bikezilla** [comment]
Hi Alex - Vladimir from Receipt-Bank here.

I'd second the preference order put forth by @P-Tracy.

**Comment by andyws** [comment]
I suggest chattiness will be an immediate problem while throttling is tied to an application rather than a utr.  

Am I correct in my understanding of the current and intended throttling policy?  

Will all applications have the same throttling limits or will these limits vary by vendor/application?

**Comment by andyws** [comment]
Option 3.  With the proviso that you provide a collection of all errors each of which is identifiable and with a reason.

**Comment by P-Tracy** [comment]
Can I just clarify - is chattiness a problem because of the application of the throttling rules on the HMRC API Gateway as opposed to because of the non-functional scalability of the architecture?  If it's throttling, can we not work together to define a better algorithm or throttling criteria?

I personally don't think creating larger resources that combine lists of different resources in a single transaction will be workable long-term.  It kind of flies in the face of REST.  

When we break it down, if I give you a list of 12 expenses, 8 incomes and 3 charges, are you going to attempt to process all 23 of them and give me a full list of errors?  Or are you going to fail on the first one, in which case I end up sending the request multiple times anyway with a larger payload just to get it to process in its entirety.

If it's a scalability issue with the implementation, could it not be redesigned to be more elastic and adaptable?  The peaks will be large, but shallow, no?  So if the scaling rules are correct, the platform will swell but for a small period of time, and it will reduce again in a short time frame too?

**Comment by andyws** [comment]
Pauline,

I feel chattiness and throttling intersect, but they are distinct.  

Throttling is an issue because as far as I can tell it is based on an application.  So if you have a webapp servicing multiple distinct clients( = distinct utrs  ) and making multple calls on their behalf to HMRC you may hit the throttling limit.  It is easy to create a test script which hits the throttling limit in the sandbox.  I am not aware of documentation which states what the throttling limit is in test or production.

'Chattiness' is inherent in a HATEOAS based system.  If patterns of usage are clear 'chattiness' can be minimised to some extent by embedding content rather than linking.  

I contend on the basis of the assumptions made that running a large scale webapp and interfacing to the throttled HMRC SA HATEOAS api will at best be somewhat fragile, will require retry logic and client expectation management.

This is not to say that similar issues won't arise if the throttling is done at a UTR level but they will be less likely and have the advantage of making the webapp architecture more manageable.

**Comment by andyws** [comment]
Pauline,

I like option 3 because it offers easier state management.  

Suppose I collect a set of data from a client over several 'pages' for which there is local validation, ie the state is held on the client or in my webapp.  Once they have completed the exercise they press submit.  I would prefer to send the whole lot in one go and, if there are errors, to be able to indicate issues as a whole.  I would want all of the errors in one go and absolutely not just the first!

I would hate to find I had got halfway through a 'business' transaction to find I could not commit the other half either because of the last item submitted tripped an HMRC rule for instance.  I might be faced with waiting to retry submitting the second half or much much worse having to unwind the first half.

**Comment by P-Tracy** [comment]
@andyws 

I see your point, but I would manage that in my middle tier by kicking off multiple transactions against the  HMRC APIs in parallel and collecting the responses. We can accept and display the data to the User in any granularity we choose, it doesn't necessarily correlate with the transaction scope of the dependency.  I don't have to physically send the data in a single transaction.  

FYI we will very much be maintaining the state of the User's interactions locally until the end of the quarter, mainly as HMRC have yet to document the logic around interim edits to that data or states of that data.  Therefore, we will store the data locally for 3 months and do a submit at the end prior to but close to the deadline.

The only time we want to submit in a single transaction, where this is relevant, is if the transaction scope of the commit is related, but in this scenario that is not the case; if income 4 fails, I still want income 1-3 to be accepted.   If an income fails, I still want all my expenses to be created. So the transaction scope is actually the scope of the resources as they are currently defined, i.e. income, expense, balancing charge etc.

As long as the API can accommodate me doing one resource per transaction, and other consumers bundling them, then I'm happy.

The risk I would raise with the bundling is that I do not want to have to code bespoke logic against an error response in the body - when if I was submitting a single resource a standard HTTP Status Code would suffice.  This for me would not be ideal.

**Comment by andyws** [comment]
@P-Tracy 

I understand your design choice ... may the best software win! ;-)

Have you undertaken any testing at scale against the HMRC api?  I would be interested in swapping notes.

**Comment by andyws** [comment]
@P-Tracy 

"..as HMRC have yet to document the logic around interim edits to that data or states of that data. "

This is troubling...

**Comment by alexec** [comment]
Just to update this thread:

We are looking to update he API to reduce the number of requests necessary to update HMRC. This is to ensure that the systems will be able to support the January peak load. This is likely to result in more coarsely grained resources.

 > 29 January was the busiest day with 513,271 returns completed – that’s more than 21,386 returns received per hour. The busiest time was between 14:00 and 15:00, with 50,358 customers – 14 per second – clicking submit.

https://www.gov.uk/government/news/another-record-breaking-year-for-self-assessment

We are not sure how taxpayers and agents will behave in and MTD world, so this is a guideline only. The public beta is not expected to reach all 

We are aware that the current throttling will probably be to low to allow for this level of throughput and needs to be addressed.

For a REST API,  the whole request to be committed atomically. If any part fails, then the whole request fails an no changes are committed. The reason for failure is returned to the client. We can return the reason for failures (one or more errors). Rough example:

~~~
{
   "code": "VALIDATION_ERROR",
   "message": "Validation failed",
   "errors": [
      {"code": "INVALID_FIELD", "message": "This field is invalid", "path", "/allowances/captialAllowance"},
      {"code": "NEGATIVE_AMOUNT", "message": "This field is negative and must be positive", "path", "/adjustments/lossBoughtForward"}
   ]
}
~~~

**Comment by P-Tracy** [comment]
Hi Alex. 

Thanks for that. 

I thought public beta was going to be around 400,000 tax returns? If this is the case the actual transaction volumes in IT terms are going to be very small. Even 14tx/second is quite low if using scalable, reactive cloud technologies no? 

The response you provided there was what I was worried about. I realise the existing APIs are missing the quarterly filing dates, but other than that they conform to standard REST standards which we were really happy with. It meant we didn't have to worry too much about the responses as we are able to take a lot of that out of the box. 

With this new bespoke response payload that I now need to parse, this makes it difficult for me. I'm not happy with that. 

Is there no way the transaction volumes can be accommodated in the infrastructure rather than changing the contracts?  I realise they are far higher than the status quo, but in banking or gambling terms they are a drop in the ocean. There are tried and tested mechanisms for scaling to accommodate shallow peak loads. 

Not to mention the opportunities for queuing and distributing the loads

**Comment by andyws** [comment]
@P-Tracy 

Given the current fine grained HATEOAS api approximately how many http requests will be required per SA submission?

**Comment by P-Tracy** [comment]
Well, I guess that depends what we are using the linked responses for.  

So far I've not seen very much metadata associated with the link, but this is how to people usually minimise the need to physically retrieve the resource.  For example, if we are provided say the name or type of the resource as the metadata, then we can display the link to the resource with enough contextual information to only have to retrieve it when the User initiates the need to see the full resource.  

If HMRC are able to flesh out some of the key information about each resource and provide in the body of the message then I think these problems may go away.  So far the documentation hasn't specified this.  

However, the key elements of HATEOAS, i.e. the state has not been documented either, which for me is critical to understand what the workflow and user experience is.

**Comment by P-Tracy** [comment]
Another option is to support media types in the header, where an API consumer with the appropriate permissions can request the full or a richer resource than the default.  

The SLAs will generally be larger for these (for obvious reasons) but this does minimise the traffic for clients using technologies that find it difficult to support parallel transactions or multiple requests.  

So, an approved client could pass in a media type of say 'verbose' and if they have permissions, they'd get the full SA or the most important parts of the SA back in the response without having to issue multiple retrieves.

But - it means the normal behaviour remains as linked responses, which in modern frameworks are preferable.

**Comment by P-Tracy** [comment]
@andyws Sorry Andy - I don't know how many HTTP transactions are required.  I'm not from a tax background so I've been asking for scenarios for SA submissions to attempt to map these to a set of API requests.  

We are still trying to figure out exactly what the normal transition through a quarterly filing period would be, but given there are no published state machines it's proving difficult.  

Saying that, given the resources are all (at the moment) autonomous I am happy to fire these off in parallel to minimise my E2E response time.  Transaction numbers may be high, but hopefully we can minimise the execution time

**Comment by andyws** [comment]
@alexec 

How practical would it be to include a 'path' in an error item?

**Comment by andyws** [comment]
@P-Tracy 

'However, the key elements of HATEOAS, i.e. the state has not been documented either, which for me is critical to understand what the workflow and user experience is.'

In one sense a HATEOAS api is its own documentation and the documentation is the api.  I have yet to find a good example of a HATEOAS api described usefully in any meta language.

**Comment by alexec** [comment]
Thank you for your feedback.

Regarding the `path`, this is an XPath to the element that cause the problem. This me allow you to highlight the problem with the data.

**Comment by andyws** [comment]
Doh!

Sorry Alex, I need new spectacles...

**Comment by P-Tracy** [comment]
Hi @andyws 

Generally pay pal API has the best stab at HATEOAS as the engine of state; they only release the subsequent states via a link once you've met the criteria.  So they completely control the state machine from within their codebase.  

https://developer.paypal.com/docs/api/

Not sure if this was what you were asking....

I don't necessarily want any meta-language.  At the moment the links to the sub-resources are being returned literally as links, with no metadata to describe them - this is not wrong by any means, it just means we're missing a trick with the ability to return enough so people don't have to retrieve every resource.

**Comment by andyws** [comment]
@P-Tracy 

Interesting.  On a quick inspection I couldn't see a Swagger/Raml spec.

**Comment by P-Tracy** [comment]
Ah sorry. No idea 

I just read the api spec on the site itself ...

**Comment by alexec** [comment]
Thank you for your feedback.

**Comment by alexec** [comment]
Mohsin @ WK:

> Our current on premise application works at source level hence it feels like Option2a would be the best choice, I like it because it gives us  ability to remove items as well. If I would have to pick an order I would say:
2a, 2b, 1, 3
 
> I think 1 is too granular but if we have support for HTTP/2 multiple requests it might work fine. Option 3 I think it will cause to much data traffic
