### ISSUE TITLE
Request for feedback on a new version of the API

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#229]
A request for feedback on the working draft of the next version of the API.

[Open RAML](https://github.com/hmrc/self-assessment-api/pull/228)

**Comment by andyws** [comment]
Good man!  Thanks for providing this.

I had a quick glance over the raml.  The only point I would raise initially is that to/from are typed as strings rather than dates.

Over the next few days I will create a server from the doc and test my client against it and create clients from the doc and test it against the hmrc sandbox.

Regards

Andy

**Comment by alexec** [comment]
Hi Andy, I should mention this spec is proposed at the moment and we've looking to get feedback.

**Comment by andyws** [comment]
Hi Alex,

There seems to be an issuette wrt PrivateInsurance, there being no schema for said type.

Andy

**Comment by alexec** [comment]
Try now.

**Comment by andyws** [comment]
Ta

**Comment by andyws** [comment]
For the avoidance of doubt can you clarify why both v2 and v1 exist?

**Comment by alexec** [comment]
Hi @andyws ,

Sorry for the delay in my reply. We plan to incrementally release part of the API. v1 contains what is considered MVP, whereas v2 shows patterns for resources we'll be adding later on.

**Comment by alexec** [comment]
Thank you for your feedback.
