### ISSUE TITLE
Liability calculations - anticipated behaviour

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#240]
Hello

Are we expecting people to request their liabilities multiple times throughout the tax year, so prior to quarterly submissions?  Or is this anticipated (in the HMRC models) to remain an annual thing that they do only when all the quarterly and annual data is available?  

Will liabilities only be calculated by a user-initiated trigger or can it also be done by HMRC in the background?

Thanks

**Comment by andyws** [comment]
In the absence of being told otherwise we have one stream in which we assume that any SOI change will automatically trigger a liability calculation.  We would like this to be the case because it opens the door to be able to offer what-if 'official' estimates.

Whether such usage will be allowed - who knows?

We would like hmrc to add a notification service so that when a liability changes we can be notified of the change and the input(s) which prompted said change.  I have see no such proposal from hmrc.

**Comment by P-Tracy** [comment]
@andyws Quick question - what does SOI mean?

As an aside - we've asked HMRC for notifications for any business-significant changes to the data as they're now the master and they've added this to the backlog or at least sent these requests to the 'Messaging Team'.

**Comment by hicnar** [comment]
@P-Tracy 

Thank you for your enqury.

The self assessment api will provide an endpoint to request liability calculation and in this stage of the project there are no known limitations as to the frequency of liability calculation requests. 

At the same time it is important to bear in mind that the outcome of liability calculation is determined by the data that HMRC is aware of. As a consequence, all income from business sources will need to be submitted via the api in order to be taken into account for liability calculation.

Technically speaking, liability calculation could be triggered by HMRC in the background but again, because the liability resulting from calculation depends on the data provided by the user at this stage, it is intended to be initiated by users as they update their records.

Hope this clarifies your doubts

**Comment by andyws** [comment]
source of income

**Comment by P-Tracy** [comment]
@andyws Not 100% sure who the Messaging Team are but they were mentioned in a chat we had a few months ago.  I do not have visibility of their backlog I'm afraid.  Maybe @alexec could point us in their direction?

**Comment by P-Tracy** [comment]
@hicnar Thanks for the reply

Just for my own clarification, and I know the SA states are not published yet, but if a consumer requests a liability calculation and the data is incomplete, will the response indicate that it an 'estimate' or 'indicative' figure?  

I'm just trying to figure out how the states and the logic will work - and to make sure that the intelligence about the legitimacy of the accuracy of the liability is on the HMRC side and not ours?

From a usability perspective, I think we would make the ability to calculate available from the outset as that would be seen to be a value-add in the new world, I would think.  But I'd like to understand a little more how this will work...

**Comment by hicnar** [comment]
@P-Tracy 

The liability calculation result is based on the data that HMRC is aware of at the point of calculation, therefore all in year liability calculations will be estimates and the liability would not be binding on the taxpayer in any way.

It is only at the end of the tax year when HMRC has complete information about incomes from all sources when a crystalised liability can and will be calculated.

Hope that helps!

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy, I'm going to close this issue due to inactivity. Please open another if you would like to discuss this further.

Thanks,
Jacob
