### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#264]
The main link to the SA documentation provides a message: 

```
Self Assessment API
This API documentation is being updated, but you can still access it here.

```

This has been like this for at least a day.  Is there an issue?  The link attached to the above message is: [https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api?service=self-assessment-api#self-assessment-api](https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api?service=self-assessment-api#self-assessment-api) 

Will the pending new documentation amend the API?

As there seems to be no immediate prospect of a RAML spec for the API I propose to reverse out a spec based upon the documentation and running code.  IMHO and as I have oft stated I find this less than satisfactory.  However can you indicate whether the following assumptions wrt any node in the HATEOAS graph are reasonable:

1. The documentation always lists all possible links on a node.
2. All documented links on a node are optional unless stated otherwise
3. The documentation always lists all possible embedded nodes on a node.
4. All documented embedded nodes on a node are optional unless stated otherwise
5. The documentation always lists all possible state/properties on a node.
6. All documented state/properties on a node are optional unless stated otherwise

**Comment by andyws** [comment]
WRT RAML, RAML_Hotfix looks interesting.  

Would it be sensible to use this against the current sandbox?

**Comment by andyws** [comment]
Can you provide the 4 missing references?

#%RAML 1.0
---

title: Self Assessment
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: **!include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md**
 - title: Errors
   content: **!include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md**

mediaType: [ application/json, application/hal+json ]

uses:
  **sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml**
  **headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml**

**Comment by rakeshavasarala** [comment]
Hi Andy,


**Reg: Documentation on [API Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api )**
The documentation on [API Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api ) for self-assessment-api corresponds to tag [v0.61.0](https://github.com/hmrc/self-assessment-api/releases/tag/v0.61.0). 

If you have checked documenation for any other API (except self-assessment-api) in last week, you will notice that the documentation is now styled to look like RAML. Only changes have been to how the documentation looks and styled. 

I think you may have bookmarked this link
https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api?service=self-assessment-api#self-assessment-api .

Can i suggest you go to https://developer.service.hmrc.gov.uk/api-documentation/docs/api and navigate to self-assessment-api.

.
.

**Reg: RAML_Hotfix branch/tags**

This branch is still under development.

Changes in this branch are only for styling the existing documentation for self-assessment-api on [API Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api ) to look like RAML. In terms of API resources, there is no change on this branch. 


Regards
Rakesh

**Comment by andyws** [comment]
Thank you for your suggestions.  

**If I understand you correctly you are stating that HMRC is only using RAML to enable 'styling the existing documentation for self-assessment-api'.**  




fwiw  as a matter of interest the SA page on the hub emits this:

![image](https://cloud.githubusercontent.com/assets/19880258/20663542/cc59ec8c-b54f-11e6-9e02-20c6765e47f1.png)

Clicking on 'here' takes me to: [https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api?service=self-assessment-api#self-assessment-api](https://developer.service.hmrc.gov.uk/api-documentation-old/docs/api?service=self-assessment-api#self-assessment-api)

**Comment by rakeshavasarala** [comment]
Yes, the self-assessment-api documentation on API Developer Hub is still in old styling. Work on **RAML_Hotfix** branch is to fix that. As i mentioned earlier, **RAML_Hotfix** branch would only update the style of documentation and not the specification.


The word *RAML* is very confusing. Let me try to explain it.

- The documentation on the API Developer Hub, irrespective of how it looks in terms of styling, should alway match the API specification that has been developed, tested internally by HMRC and deployed to both SANDBOX and PRODUCTION environments. The API Platform team who manage the documentation for all HMRC API's (not only SA), decided to change the documentation styling to look like RAML. This part is still WIP for self-assessment-api and will be fixed by **RAML_Hotfix** branch.

- On other hand, we, the self-assessment-api team are trying to change the API Specification, resources. This relates to your issue https://github.com/hmrc/self-assessment-api/issues/259. Before we start coding, we wanted to get feedback got internally and from 3rd party vendors, so we use RAML to generate the API Specification.

Hope this is a bit more clearer.

**Comment by andyws** [comment]
> The word RAML is very confusing. Let me try to explain it.

I'm not sure how to take this.  

_______________________________________________

I am tracking RAML_Hotfix and MTDSA-623 etal.  I have for some time been looking for an SA API spec which I can use to generate code and tests.  

RAML_Hotfix (1.0) needs amendment before it validates as per my above previous comment.  Any thoughts?

MTDSA-623 etal (0.8) is too volatile at the moment and requires too much patching for this purpose.

Have I missed any other streams?

I presume that at some point there will be a single SA spec which will be used for multiple purposes including generating API documentation?  Apart from my exchanges have any other 3rd party developers commented on the RAML?

Given the absence of a spec I can use can you indicate whether the following assumptions wrt any node in the HATEOAS graph are reasonable in my attempt to reverse out the spec from the documentation:

1. The documentation always lists all possible links on a node.
2. All documented links on a node are optional unless stated otherwise
3. The documentation always lists all possible embedded nodes on a node.
4. All documented embedded nodes on a node are optional unless stated otherwise
5. The documentation always lists all possible state/properties on a node.
6. All documented state/properties on a node are optional unless stated otherwise

**Comment by rakeshavasarala** [comment]
Andy,

Regarding *RAML_Hotfix*
I am not sure why you are tracking code on the branch's. You should only be traking 'master' branch unless someone from the self-assessment-api team has pointed you in the direction of a particular branch.


Regarding your questions
I assume all your questions are regarding documentation on the API Developer Hub, as they mention HATEOS. 

The documentation always lists all possible links on a node. 
      - **Yes**. When you create a source (lets say self-employment) it lists all the possible summaries (incomes, expenses ...) in links along with self link for the created source.
All documented links on a node are optional unless stated otherwise 
      - **Yes**
The documentation always lists all possible embedded nodes on a node. 
     - **Yes** Currently the 'Retrieve All' calls do not support pagination so they return all the immediate childs.
All documented embedded nodes on a node are optional unless stated otherwise.
     - **Yes**
The documentation always lists all possible state/properties on a node. 
    - **Yes** for properties. Not sure what do you mean by state.
All documented state/properties on a node are optional unless stated otherwise
    - **Yes** for properties. All create/update requests specify mandatory/optional for fileds. Not sure what do you mean by state.

Regards
Rakesh

**Comment by andyws** [comment]
> I am not sure why you are tracking code on the branch's. You should only be traking 'master' branch unless someone from the self-assessment-api team has pointed you in the direction of a particular branch.

> I am tracking RAML_Hotfix and MTDSA-623 etal. I have for some time been looking for an SA API spec which I can use to generate code and tests.

> Apart from my exchanges have any other 3rd party developers commented on the RAML?

**Comment by alexec** [comment]
Hi Andy,

The API specification is still in a state of flux. I hope this is not a problem for you.

We've had feedback from developers, but naturally we cannot comment on what they have said.

I believe your questions have been asked now? We can re-open if you have further questions

Closing ticket.

Alex
