### ISSUE TITLE
How do I 'meet' the obligation?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#343]
If the workflow is:

1. I submit my 1..* Periods to cover the obligation dates
2. I the POST for a calculation (to let HMRC know I'm done)
3. How do I know that I have failed to comply?  How do I find out that I a missing a day in the range?  Or that I have an overlap or some other issue that meant my obligation couldn't be changed to 'met'?

Do I have to keep re-retrieving the obligations to see if I was successful?  
And if it doesn't change to 'met' how do I find out what went wrong?

Actually  - can you just outline the end to end workflow in terms of minimal API transactions to get me from nothing to successful obligation 1 completion?

**Comment by andyws** [comment]
On a related note, is it the case that a calculation can only be triggered once per day, that subsequent triggers will be ignored in the sense that the liabilities returned will NOT reflect updates post the initial calculation trigger for a specific day?

Is it the case that I cannot tell and cannot find out which inputs have contributed to the liability statement that I receive?

Is it the case that triggering a calculation has no significance wrt signifying the closure of an obligation period?

Once again I would offer the opinion that specifying an API is not sufficient, the expected behaviour/use cases needs to be clearly provided as well.

**Comment by alexec** [comment]
Raised with TDG. Awaiting response.

**Comment by P-Tracy** [comment]
@alexec Any update on this?  This is my number one issue and risk at the moment.  

My concern is I may need to poll the obligations resource.  I don't want to poll.  It's a headache and costly.  And will use up my tiny allocation of transactions I've been given!  

Can you chase this as a matter of urgency?

**Comment by sudoku007** [comment]
Hi P-Tracy,

I forwarded the issue to the relevant team asking for the response from them on this issue. Once we get a response back from them will pass it onto you.

Regards,
Chandra
