### ISSUE TITLE
403 CLIENT NOT SUBSCRIBED

### ISSUE THREAD

**Issue by PandoraMiller** [hmrc/self-assessment-api#493]
Hi,

I have exactly the same problem as this previous issue:
https://github.com/hmrc/self-assessment-api/issues/447

However the proffered solution does not work as I need a National Insurance number for the
self-assessment/ni/{nino}/self-employments POST test request.

Using a previously generated nino from creating an individual test user does not work.

Thank you

**Comment by sudoku007** [comment]
Hi,

As mentioned in #447 

Could you please use **Create a test user which is an organisation (/create-test-user/organisations)** end-point instead of Create a test user which is an individual (/create-test-user/individuals) for creating Test user.

Once the test user is created as an organisation, can you try again using that nino for the organisation.

Regards,
Chandra
