### ISSUE TITLE
Getting 403 on hitting https://api.service.hmrc.gov.uk/oauth/token

### ISSUE THREAD

**Issue by sri-akshat** [hmrc/self-assessment-api#513]
https://api.service.hmrc.gov.uk/oauth/token returns a 403 access denied. Is there some whitelisting that needs to be done for our IP ?

**Request Body** -
client_id - YHqyQK7ijlVspw2Po8yVyfWJ9Ywa
client_secret - ***
code - ***
grant_type - authorization_code
redirect_uri - https://partnerauth-qal.platform.intuit.com/external_partner/hmrc/callback

**Response Code** - 403
**Response Header** -
appId=1047*
ctrlguid=1505451774*
acctguid=3b662425-b849-4961-afd2-c0d77ddcf9d0*
ts=1506664373131btid=37881guid=14538472-dcf9-40ac-8d9d-23effd10b45dexitguid=4unresolvedexitid=67982cidfrom=5354

**Comment by rakeshavasarala** [comment]
@sri-akshat 

Apologies for the delay in replying. 

Last week, we did urgent maintenance work on our HMRC Developer Sandbox environment. You might have received an email from SDST (SDSTeam@hmrc.gsi.gov.uk) about this.

This is impacting accessing the self-assessment-api as well as all other API's on the Sandbox environment. We are working with the relevant teams within HMRC to get it up and running.

We will update you once Sandbox environment is stable.

**Comment by rakeshavasarala** [comment]
@sri-akshat 

The environment has been stable from yesterday afternoon. 
Could you please retry your request and let us know if the issue still persists.

**Comment by deeNainani** [comment]
@rakeshavasarala 
We are still getting 403.
A little investigation from our side shows that we get the 403 when we are hitting the https://api.service.hmrc.gov.uk/oauth/token using the proxy for which the IPs are listed below:
199.16.139.32/35
206.108.45.11/16
206.108.40.179
206.108.40.183
Could you please help us out in white-listing the above mentioned IPs.

**Comment by rakeshavasarala** [comment]
@deeNainani 

Apologies. Just realised that the url mentioned in the issue is for Production and my response was for Sandbox environment.
Access to our API is not restricted based on IP's.

There are no known issues with OAuth process in Production. 

Can I please request you to email SDST at SDSTeam@hmrc.gsi.gov.uk with the issue. As this is a production issue, you may not able to share any details of your application or NINO required for investigation on Open Github.
