### ISSUE TITLE
SA - ServiceUnavailable

### ISSUE THREAD

**Issue by immanuelarun** [hmrc/self-assessment-api#537]
Hi,

On hitting the base URL --> https://test-api.service.hmrc.gov.uk for Adding a Self-employment business (/self-assessment/ni/{nino}/self-employments) api method is returning the following response.

ServiceUnavailable

Is there any maintenance or downtime?

**Comment by hicnar** [comment]
It's been a while @immanuelarun but do you still experience the same problem?

**Comment by tbm** [comment]
@hicnar now you get

```
{ "code" : "NOT_FOUND", "message" : "The requested resource could not be found." }
```

**Comment by jacobbrownlow** [comment]
Hi @immanuelarun 

Apologies that this issue was overlooked.

I have just tried adding a SE business in the sandbox and it is working
![image](https://user-images.githubusercontent.com/35334115/43194028-58924fa2-8ff9-11e8-9de6-4c20699249f5.png)

Please let us know if this is still an issue.

Regards, Jacob
