### ISSUE TITLE
Self Assessment (MTD) API  --> List all self-employment businesses

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#739]
Hey there,
when i am trying to call the API for the same with correct NINO number,access token and proper headers i am getting the response status as OK but content as empty.

Thanks

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore,

`List all self-employment businesses` is one of the older stateful APIs, which was built before the steer was to make our stubs stateless. In order to use this endpoint, you need to hit the `Add a self-employment business [test support]` endpoint to set up your data. See https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#selfemployment-business_add-a-selfemployment-business-test-support_post_accordion for more information on that endpoint.
