### ISSUE TITLE
Submit Self-Employment End-of-Period Statement

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#744]
hey there,

I need to have some clarification on Submit Self-Employment End-of-Period Statement API.

1. In this endpoint, we will be sending the finalised flag for the whole Accounting period or each quarter?

2. Once the finalised flag has been submitted to HMRC post which can an individual submit/amend the quarterly submission or not?

3. What is the deadline for submitting the finalised flag in this API?

Any help would be much appreciated!

Regards

**Comment by mtd-api-team** [comment]
:this:
Hi @heythisiskishore,

1. You are sending the finalised flag for the whole accounting period.
2. Yes they can, but they would need to re-submit their SE EOPS.
3. The due date on the EOPS obligation, typically 31/01 following the end of the tax year in which this accounting period falls.

Hope this helps.

**Comment by heythisiskishore** [comment]
hey there,

Thanks for your quick response!

Further to your response on Point no 2, we have found one HMRC error as below:

HTTP status: 403 (Forbidden), Code: RULE_ALREADY_SUBMITTED
You cannot submit a statement for the same accounting period twice.

As per your previous response, user can re-submit their SE EOPS, however, HMRC will display an error if user will re-submit SE EOPS.

Any help or guidance would be much appreciated!

Thanks in advance.

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore,

The `RULE_ALREADY_SUBMITTED` error is returned when HMRC have not recorded any changes to the periodic updates or annual summary data supplied, since the EOPS submission for this accounting period.

Updates to the periodic or annual data, after an EOPS submission, will invalidate the existing EOPS and a new EOPS submission is required. However, if no changes have been made, then any subsequent EOPS submission (for the same accounting period), is a duplication and will be rejected with this error.

I hope this clears things up. If you have any further questions please respond to this thread and we'll be happy to answer them.
