### ISSUE TITLE
FHL and Other Property Obligations

### ISSUE THREAD

**Issue by johnhemming** [hmrc/self-assessment-api#749]
First Question:

I am wondering what needs to be done to change a self assessment property obligation from not met to met.  Does it require a submission of  both and FHL and an non-FHL obligation for that period?

Or does it require only one to be submitted?

Second Question:

Are the obligation dates always quarters of the tax year or can they be something else or defined by taxpayer (or their agent)?

**Comment by mtd-api-team** [comment]
Hi @johnhemming 

> I am wondering what needs to be done to change a self assessment property obligation from not met to met. Does it require a submission of both and FHL and an non-FHL obligation for that period?

For sandbox, the obligation responses are canned, so in order to show the obligation as 'met' you will need to use the gov-test-scenario provided.
In production, a property obligation will be shown as 'met' as long as a period has been submitted for either fhl or non-fhl. 


> Are the obligation dates always quarters of the tax year or can they be something else or defined by taxpayer (or their agent)?

The obligations are always shown as quarterly, but the user can submit multiple periodic summaries within a quarter.

Thanks,
@mtd-api-team
