### ISSUE TITLE
Test environment  intent-to-crystallise not working as of 2020-11-07T16:22:47

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/self-assessment-api#788]
* **I'm submitting a Bug in test environment **
  - [ x] Bug - API

* **What is the current behaviour?**
 https://test-api.service.hmrc.gov.uk/self-assessment/ni/AN009133D/2019-20/intent-to-crystallise postData={}
status = 404

* **What is the expected behaviour?**
 https://test-api.service.hmrc.gov.uk/self-assessment/ni/AN009133D/2019-20/intent-to-crystallise postData={}
status = 200

It worked in the past (for different test user )

Internal HMRC call to  https://test-api.service.hmrc.gov.uk/self-assessment/ni/AN009133D/calculations/041f7e4d-87d9-4d4a-a296-3cfbdf92f7e2 fails and header contains invalid "x-correlationid":"zzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"

**Comment by hmrc-api-team** [comment]
Hi @alexei-serjantov 

The response of the endpoint Intent to Crystallise is a 303 redirect. Depending on the settings of your application it may try to redirect you automatically.

Unfortunately it is redirecting to a now deprecated endpoint. You will need to store the calculation ID and use the new [Calculations API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0)

Regards Jacob

**Comment by alexei-serjantov** [comment]
Dear Jacob,

I already use  Individual Calculations (MTD) API v1.0 (Beta)  in my
application.
However there is no direct replacement for intent-to-crystallise API call
there.
Are you saying that 'intent-to-crystallise' is obsolete and should not be
used
or should it still be used, but my application settings need to change ?
What settings of my application do control this behavior  (application is
redirected automatically to a now deprecated endpoint) ?
Who is responsible for that and what should be my actions to change these
settings.


Kind regards
Alexei Serjantov

**Comment by hmrc-api-team** [comment]
Hi Alexei, 

We are working to move endpoints out of the [self-assessment-api](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0), and there will eventually be a new 'intent-to-crystallise' endpoint available, but for the time being the one you are using is correct. 

However it was built to redirect the user to 'retrieve a tax calculation' within the same service. We have since replaced the trigger and retrieve tax calculation endpoints with [individuals-calculations-api](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0).

The correct journey would be to call 'intent-to-crystallise' and capture the location header in the response, to store the calculation ID returned. Ignore the 303 redirect and instead call the new tax calculation endpoints. 

Regards

**Comment by shaunl23** [comment]
Does this apply for the issue I'm having at https://github.com/hmrc/self-assessment-api/issues/787 which hasn't had a reply?
So we need to use the ID returned from Intent to Crystallise, but in the new Individuals Calculations?

Thanks

**Comment by alexei-serjantov** [comment]
Thanks for clarification.

**Comment by ac000** [comment]
@hmrc-api-team

> However it was built to redirect the user to 'retrieve a tax calculation' within the same service. We have since replaced the trigger and retrieve tax calculation endpoints with individuals-calculations-

> The correct journey would be to call 'intent-to-crystallise' and capture the location header in the response, to store the calculation ID returned. Ignore the 303 redirect and instead call the new tax calculation endpoints.

Hmm, wouldn't it be better to just update the 'Location' header?

 /individuals/calculations/{nino}/self-assessment/{calculationId} looks like a drop in replacement for  /self-assessment/ni/{nino}/calculations/{calculationId}
