### ISSUE TITLE
list uk property gives 404 if there are no properties while list self employments returns an empty list

### ISSUE THREAD

**Issue by python-mtd** [hmrc/self-assessment-api#810]
* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [X ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**
When calling self-assessment/ni/{nino}/self-employments when there are none you get a 200 response with a body of [] (empty list)

When calling self-assessment/ni/{nino}/uk-properties when there are none you get a 404 response with an empty body (N.B. You do not get the usual json "no such endpoint" response for a 404)

* **What is the expected behaviour?**
These should be consistent (and ideally work like the self-employments one)

**Comment by hmrc-api-team** [comment]
Hello @python-mtd,

Thank you for your feedback. We aren't permitted to make (non-bugfix) changes to any of the endpoints on this API due to its age. There are, however, ongoing plans to replace the self-employments resources found here with a new implementation so I will be sure to pass your feedback onto the relevant people.

Kind regards,
MTD-API-Team
