### ISSUE TITLE
State-benefits list MATCHING_RESOURCE_NOT FOUND

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/self-assessment-api#839]
The following API call in Sandbox environment to list user benefits fails.

2021-11-04T15:52:18.949 INFO  resource=> /individuals/state-benefits/KK031210D/2019-20
2021-11-04T15:52:19.000 INFO status=404

My application  SE_reports is subscribed to the Individuals State Benefits (MTD).

The HMRC documentation for this call is ambiguous in regards to the "benefitId" parameter.
I quote:
1. "A National Insurance number, a tax year that ended, and benefit ID **must be** provided."
2. "Query Parameters
benefitId
string
**optional"**

Please help me to understand where do I go wrong.

**Comment by hmrc-api-team** [comment]
Hi @alexei-serjantov, just to confirm you are trying to call the [List State Benefits](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individuals-state-benefits-api/1.0#List%20State%20Benefits) endpoint?

You are correct, `benefitId` _is_ an optional query parameter. I will raise a ticket to get the wording changed on this, thank you for pointing it out.

I'm not sure why you would be getting a 404 response when calling the endpoint with a query parameter though - the downstream stub should return a single HMRC held state benefit when a `benefitId` query parameter is present, provided it is a valid `benefitId`. You should also get a success response without providing a `benefitId`.

Please could you confirm the full URL you are calling? Looking through our logs I cannot see a request to the Individuals State Benefits API in Sandbox in the past 24 hours with that NINO. It should look like this: `https://test-api.service.hmrc.gov.uk/individuals/state-benefits/KK031210D/2019-20`.

Also, per the [Support](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individuals-state-benefits-api/1.0#support) section on this API's documentation page please could future issues regarding Individuals State Benefits API be raised on the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues) GitHub page? That just helps us keep all Issues in one place rather than split over multiple individual APIs.

Kind regards

**Comment by alexei-serjantov** [comment]
Thank you for your prompt reply.
The URL was wrong indeed.  Issue closed.
