### ISSUE TITLE
Release 0.37.0

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#93]
Has this been pushed to the developer api hub and to the test environment for 3rd party devs?

**Comment by rakeshavasarala** [comment]
Latest Release on Developer Hub is: https://github.com/hmrc/self-assessment-api/releases/latest

The github releases tagged as 'Pre-Release' are not made available to 3rd party devs.

The [change log](https://github.com/hmrc/self-assessment-api/blob/master/CHANGELOG.md) includes the details of release to 3rd party Devs and changes on master branch since last release.
