### ISSUE TITLE
New self-employment

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#99]
Using the current release: 0.26

I am trying to create a self-employment soi as per the api docs (  [https://developer.service.hmrc.gov.uk/api-documentation/docs/api/self-assessment-api/1.0/Create%20Source] )

Does the Sandbox support such requests?  Assuming it does what have I missed?  

Regards

Andrew Smith

**REQUEST**

POST https://api.service.hmrc.gov.uk/self-assessment/8000013711/2016-17/self-employments HTTP/1.1
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer 7a64f0f423528ff351a744f644f426d3
Host: api.service.hmrc.gov.uk
Cookie: api-gateway=fcedfc6d4895b9df20ad85b0b015840c
Content-Length: 639
Expect: 100-continue
Connection: Keep-Alive

{
  "name": "bosh",
  "commencementDate": "2016-02-02",
  "adjustments": {
    "includedNonTaxableProfits": 99.0,
    "basisAdjustment": 99.0,
    "overlapReliefUsed": 99.0,
    "accountingAdjustment": 99.0,
    "averagingAdjustment": 99.0,
    "lossBroughtForward": 99.0,
    "outstandingBusinessIncome": 99.0
  },
  "allowances": {
    "annualInvestmentAllowance": 77.0,
    "capitalAllowanceMainPool": 77.0,
    "capitalAllowanceSpecialRatePool": 77.0,
    "restrictedCapitalAllowance": 77.0,
    "businessPremisesRenovationAllowance": 77.0,
    "enhancedCapitalAllowance": 77.0,
    "allowancesOnSales": 77.0
  }
}

**RESPONSE**

HTTP/1.1 408 Request Time-out
Server: nginx
Content-Type: text/html
Vary: Accept
Cache-Control: no-cache
Content-Length: 110
Date: Tue, 07 Jun 2016 11:10:02 GMT
Connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>

**Comment by alexec** [comment]
Hi Andy, this looks like a temporary timeout from around a month ago. Can you confirm if you are getting it often please?

**Comment by andyws** [comment]
Just tried this again with the same result:

**REQUEST:**
POST https://api.service.hmrc.gov.uk/self-assessment/2000076893/2016-17/self-employments HTTP/1.1
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer 3a792ee4d7805d7d523e1fb17da1804d
Host: api.service.hmrc.gov.uk
Cookie: api-gateway=43d37ab128c9052e36b0c99cda7306fe
Content-Length: 639
Expect: 100-continue
Connection: Keep-Alive

{
  "name": "bosh",
  "commencementDate": "2016-02-02",
  "adjustments": {
    "includedNonTaxableProfits": 99.0,
    "basisAdjustment": 99.0,
    "overlapReliefUsed": 99.0,
    "accountingAdjustment": 99.0,
    "averagingAdjustment": 99.0,
    "lossBroughtForward": 99.0,
    "outstandingBusinessIncome": 99.0
  },
  "allowances": {
    "annualInvestmentAllowance": 77.0,
    "capitalAllowanceMainPool": 77.0,
    "capitalAllowanceSpecialRatePool": 77.0,
    "restrictedCapitalAllowance": 77.0,
    "businessPremisesRenovationAllowance": 77.0,
    "enhancedCapitalAllowance": 77.0,
    "allowancesOnSales": 77.0
  }
}

**RESPONSE**
HTTP/1.1 408 Request Time-out
Server: nginx
Content-Type: text/html
Vary: Accept
Cache-Control: no-cache
Content-Length: 110
Date: Mon, 27 Jun 2016 09:57:26 GMT
Connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>

**Comment by alexec** [comment]
Hi Andy - we're looking into this and we'll update you when we've diagnosed the issue.

**Comment by andyws** [comment]
Any update?

**Comment by alexec** [comment]
Hi Andy, this appears to have been overlooked. Can you confirm if you're still getting this issue please?

**Comment by andyws** [comment]
Hi Alex,

I will run my code again and get back to you, I hope by midday tomoz

**Comment by alexec** [comment]
Thank you. I'll close this issue for the time being.

**Comment by andyws** [comment]
Hi,  as requested I have just retried this with the same result.  Is the sandbox capable of processing a create request?

**Comment by andyws** [comment]
Not sure if I had permission to reopen this question

**Comment by rakeshavasarala** [comment]
Hi Andy,

I looked at the logs and for some reason the POST call never made it through the API Gateway to the Self Assessment API.

Sandbox has capability to process the create request. The Sandbox endpoint does not persist data and always returns static data.

I tried to POST to /self-employments with the same UTR and payload as yours. See below the request. 

curl -v -H "Accept: application/vnd.hmrc.1.0+json" -H "Content-Type: application/json" -H "Authorization: Bearer 913643306ff75a44ccbbfeb78f1119" -X POST -d '{"name": "bosh","commencementDate": "2016-02-02","adjustments": {"includedNonTaxableProfits": 99.0,"basisAdjustment": 99.0,"overlapReliefUsed": 99.0,"accountingAdjustment": 99.0,"averagingAdjustment": 99.0,"lossBroughtForward": 99.0,"outstandingBusinessIncome": 99.0},"allowances": {"annualInvestmentAllowance": 77.0,"capitalAllowanceMainPool": 77.0,
"capitalAllowanceSpecialRatePool": 77.0,"restrictedCapitalAllowance": 77.0,"businessPremisesRenovationAllowance": 77.0,"enhancedCapitalAllowance": 77.0,"allowancesOnSales": 77.0}}' https://api.service.hmrc.gov.uk/self-assessment/9000059969/2016-17/self-employments
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 2.16.59.42...
* Connected to api.service.hmrc.gov.uk (2.16.59.42) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: online.hmrc.gov.uk
* Server certificate: COMODO RSA Extended Validation Secure Server CA 2
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> POST /self-assessment/9000059969/2016-17/self-employments HTTP/1.1
> Host: api.service.hmrc.gov.uk
> User-Agent: curl/7.49.1
> Accept: application/vnd.hmrc.1.0+json
> Content-Type: application/json
> Authorization: Bearer 913643306ff75a44ccbbfeb78f1119
> Content-Length: 530
>
* upload completely sent off: 530 out of 530 bytes
< HTTP/1.1 201 Created
< Server: nginx
< Content-Type: application/hal+json
< Vary: Accept
< Cache-Control: no-cache,no-store,max-age=0
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Content-Length: 598
< Date: Fri, 30 Sep 2016 12:39:25 GMT
< Connection: keep-alive
< Set-Cookie: api-gateway=43d37ab128c9052e36b0c99cda7306fe; Expires=Fri, 30-Sep-2016 13:39:25 GMT; Path=/
<
* Connection #0 to host api.service.hmrc.gov.uk left intact
{"_links":{"balancing-charges":{"href":"/self-assessment/9000059969/2016-17/self-employments/57ee5cfd580000288e8e192c/balancing-charges"},"expenses":{"href":"/self-assessment/9000059969/2016-17/self-employments/57ee5cfd580000288e8e192c/expenses"},"goods-and-services-own-uses":{"href":"/self-assessment/9000059969/2016-17/self-employments/57ee5cfd580000288e8e192c/goods-and-services-own-uses"},"self":{"href":"/self-assessment/9000059969/2016-17/self-employments/57ee5cfd580000288e8e192c"},"incomes":{"href":"/self-assessment/9000059969/2016-17/self-employments/57ee5cfd580000288e8e192c/incomes"}}}

**Comment by andyws** [comment]
Ok.  How should we proceed?

**Comment by sudoku007** [comment]
Hi Andy,

I am assuming you are sending all the HEADERS you mentioned above in the POST request.

Are you getting 408 (Request timeout error) only when you send a POST request for creating self employments. But other GET requests are all working fine.

Can you try sending a POST request to create some other source like (Unearned Incomes or Furnished Holiday Lettings or UK properties)? Just wanted to check if the issue is happening only for self employments or all other sources as well.

Regards,
Chandra

**Comment by sudoku007** [comment]
Hi Andy,

I have just noticed that you are sending a header `Expect: 100-continue` in the POST request. I am wondering if the issue is caused because of this header.  

Can you try sending POST request without this header `Expect: 100-continue` and see if works fine.

Basically this header `Expect: 100-continue` enables the client to send a POST request in 2 parts. 1st part with just headers and wait for response from Server and then after acknowledgement/confirmation from Server to continue, it client sends the 2nd part with the actual body.

I think most probably what might be happening is that the Server might not have sent an acknowledgement/confirmation to the client and the client request might be timing out and throwing a 408 (Request timeout error) because of that.

Regards,
Chandra

**Comment by andyws** [comment]
Hi Chandra,

A worthwhile suggestion which I have tried out.  However I still get a 408.  Its all a bit frustrating.  I know you have tried this yourself and had success.  But could you tell me if any other 3rd Party devs are successful using this api?


`POST https://api.service.hmrc.gov.uk/self-assessment/9000097612/2016-17/self-employments HTTP/1.1
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer 2b3befc24d2eced8571da77b5526d82d
Host: api.service.hmrc.gov.uk
Cookie: api-gateway=fcedfc6d4895b9df20ad85b0b015840c
Content-Length: 639

{
  "name": "bosh",
  "commencementDate": "2016-02-02",
  "adjustments": {
    "includedNonTaxableProfits": 99.0,
    "basisAdjustment": 99.0,
    "overlapReliefUsed": 99.0,
    "accountingAdjustment": 99.0,
    "averagingAdjustment": 99.0,
    "lossBroughtForward": 99.0,
    "outstandingBusinessIncome": 99.0
  },
  "allowances": {
    "annualInvestmentAllowance": 77.0,
    "capitalAllowanceMainPool": 77.0,
    "capitalAllowanceSpecialRatePool": 77.0,
    "restrictedCapitalAllowance": 77.0,
    "businessPremisesRenovationAllowance": 77.0,
    "enhancedCapitalAllowance": 77.0,
    "allowancesOnSales": 77.0
  }
}`

`HTTP/1.1 408 Request Time-out
Server: nginx
Content-Type: text/html
Vary: Accept
Cache-Control: no-cache
Content-Length: 110
Date: Wed, 12 Oct 2016 09:53:26 GMT
Connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
`

**Comment by sudoku007** [comment]
Hi Andy,

Sorry it's proving a bit tricky and frustrating as we are not able to recreate the 408 Request timeout error locally, we are sending all the headers you mentioned above using our bearer token and it is succeeding all the time.

Please bear with us as we will get to the bottom of the problem and identify the cause and fix it.

So far we haven't heard any other Third Party Developers complain about this issue in specific. However I am not sure how many of them have actually tried sending POST request to create a source.  

I will try to check our logs and see if any Third Party Developers have successfully sent a POST request to create a source. 
 
- Can you try sending the POST request to other sources (Unearned Incomes or Furnished Holiday Lettings or UK properties). Just wanted to verify if the issue is with all sources and not just for Self Employments

- Can you also try using  sending the POST using curl from command line with all the headers and bearer code, just wanted to verify if issue is with your client code/library.

Regards,
Chandra

**Comment by sudoku007** [comment]
Hi Andy,

Would appreciate if you could try out the below 2 points and provide the feedback for the same as it would help investigate and resolve the issue.

-Can you try sending the POST request to other sources (Unearned Incomes or Furnished Holiday Lettings or UK properties). Just wanted to verify if the issue is with all sources and not just for Self Employments

-Can you also try using sending the POST using curl from command line with all the headers and bearer code, just wanted to verify if issue is with your client code/library.

Regards,
Chandra

**Comment by saurabharora80** [comment]
@andyws have you managed to resolve this issue?

**Comment by andyws** [comment]
Resolved on the Mtd beta site
